package info.vizierdb.api.websocket

/* this file is AUTOGENERATED by `scripts/build_routes` from `vizier/resources/vizier-routes.txt` */
/* DO NOT EDIT THIS FILE DIRECTLY */

import play.api.libs.json._
import info.vizierdb.types._
import info.vizierdb.api.handler._
import info.vizierdb.api._
import org.mimirdb.api.Response

object WebsocketEvents
{
  def headAction(
    action: String, 
    projectId: Identifier, 
    branchId: Identifier, 
    args: JsObject
  ): Option[Response] = 
    action match {
      case "workflow.get" => Some(GetWorkflowHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId)), new WebsocketRequestConnection(args)))
      case "workflow.cancel" => Some(CancelWorkflowHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId)), new WebsocketRequestConnection(args)))
      case "workflow.query" => Some(WorkflowSQLHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId)), new WebsocketRequestConnection(args)))
      case "workflow.modules" => Some(GetAllModulesHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId)), new WebsocketRequestConnection(args)))
      case "workflow.append" => println(args); Some(JsonHandler[AppendModule].handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId)), new WebsocketRequestConnection(args)))
      case "workflow.get_module" => Some(GetModuleHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case "workflow.insert" => Some(JsonHandler[InsertModule].handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case "workflow.delete" => Some(DeleteModuleHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case "workflow.replace" => Some(JsonHandler[ReplaceModule].handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case "workflow.thaw_upto" => Some(ThawModulesHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case "workflow.thaw_one" => Some(ThawModulesHandler.ThawOne.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case "workflow.freeze_from" => Some(FreezeModulesHandler.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case "workflow.freeze_one" => Some(FreezeModulesHandler.FreezeOne.handle(Map("projectId" -> JsNumber(projectId), "branchId" -> JsNumber(branchId), "modulePosition" -> (args \ "modulePosition").get), new WebsocketRequestConnection(args)))
      case _ => None
    }
}
